"""Dashboard (CLO3) — Professional Report Generation with full metrics export"""
import streamlit as st
import pandas as pd
import io
from datetime import datetime
import sys, os
import numpy as np
import plotly.graph_objects as go

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from components.theme import (inject_stitch_theme, sentinel_header,
                               pipeline_status_bar, section_header, COLORS, 
                               PLOTLY_LAYOUT, set_layout, save_all_figures)
from components.sidebar_settings import render_sidebar_settings
from utils.hrv_analysis import interpret_hrv, detrended_fluctuation_analysis

st.set_page_config(page_title="Report Generation · Clinical Sentinel",
                   page_icon="📑", layout="wide")


# ── report builder ────────────────────────────────────────────────────────────

def build_markdown_report(metrics_dict: dict, settings: dict,
                           sqi_cache: dict) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = []
    lines += [
        "# Clinical Sentinel — ECG & HRV Analysis Report",
        f"\n**Generated:** {ts}  |  "
        f"**Version:** Research-Grade Suite v2.0\n",
        "---\n",
    ]

    # ── 1. Methodology ────────────────────────────────────────────────────────
    lines += ["## 1. Methodology\n"]
    lines += [
        "### Signal Acquisition",
        f"- Files analysed: {', '.join(metrics_dict.keys())}",
        f"- Sampling frequency: **{settings.get('sfreq', 250):.0f} Hz**\n",
        "### Preprocessing",
        f"- Bandpass filter: **{settings.get('lowcut', 0.5):.2f}–"
        f"{settings.get('highcut', 40):.0f} Hz** "
        f"(Butterworth order {settings.get('filter_order', 4)})",
        f"- Baseline wander removal: "
        f"**{'Yes' if settings.get('remove_baseline', True) else 'No'}**",
        "### R-Peak Detection",
        f"- Algorithm: **{settings.get('rpeak_method', 'NeuroKit')}**  \n"
        "  *(Pan-Tompkins Custom implementation — CLO1)*\n",
        "### Ectopic Beat Correction",
        f"- Enabled: **{'Yes' if settings.get('remove_ectopic', True) else 'No'}**",
        f"- Detection method: **{settings.get('ectopic_method', 'median')}**",
        f"- Detection threshold: **{settings.get('ectopic_threshold', 20)}%**\n",
        "### HRV Analysis",
        f"- LF band: **{settings.get('lf_min', 0.04):.2f}–{settings.get('lf_max', 0.15):.2f} Hz**",
        f"- HF band: **{settings.get('hf_min', 0.15):.2f}–{settings.get('hf_max', 0.40):.2f} Hz**",
        f"- PSD: **Welch's method**\n",
        "---\n",
    ]

    # ── 2. Results ────────────────────────────────────────────────────────────
    lines += ["## 2. Results\n"]
    for fname, m in metrics_dict.items():
        lines += [f"### File: `{fname}`\n"]
        lines += [
            "#### Time-Domain Metrics",
            "| Metric | Value |",
            "|---|---|",
        ]
        for k in ["Mean RR (ms)", "SDNN (ms)", "RMSSD (ms)", "NN50", "pNN50 (%)", "Mean HR (bpm)"]:
            v = m.get(k, "N/A")
            s = f"{v:.2f}" if isinstance(v, float) else str(v)
            lines.append(f"| {k} | {s} |")
        lines.append("")

        if "LF Power (ms²)" in m or "LF Power (ms2)" in m:
            lines += [
                "#### Frequency-Domain Metrics",
                "| Metric | Value |",
                "|---|---|",
            ]
            for k in ["LF Power (ms²)", "HF Power (ms²)", "LF/HF Ratio"]:
                k_lookup = k.replace("²", "2") if k not in m else k
                v = m.get(k_lookup, "N/A")
                s = f"{v:.3f}" if isinstance(v, float) else str(v)
                lines.append(f"| {k} | {s} |")
            lines.append("")

    # ── 3. Clinical Interpretation ────────────────────────────────────────────
    lines += ["---\n", "## 3. Clinical Interpretation\n"]
    for fname, m in metrics_dict.items():
        interp = interpret_hrv(m, m)
        lines += [
            f"### `{fname}`",
            f"- **Overall HRV (SDNN):** {interp.get('sdnn_class','N/A')}",
            f"- **Vagal Tone (RMSSD):** {interp.get('autonomic','N/A')} (Reflects HF/Parasympathetic activity)",
            f"- **Sympathovagal Balance:** {interp.get('lf_hf_class','N/A')} (Reflects LF/HF Ratio)\n",
        ]

    lines += [
        "---\n",
        "*Report generated by Clinical Sentinel ECG & HRV Analysis Suite v2.0*",
    ]
    return "\n".join(lines)


# ── Chart & Document Generators ───────────────────────────────────────────────

def _generate_report_charts(filename: str) -> dict:
    """Generates the 6 mandatory charts for the report."""
    charts = {}
    sfreq = st.session_state.get("sfreq", 250.0)
    
    # 1. ECG Signal (Raw vs Filtered)
    raw_sig = st.session_state.get("raw_signals", {}).get(filename)
    filt_sig = st.session_state.get("cleaned_signals", {}).get(filename)
    if filt_sig is not None:
        max_idx = min(len(filt_sig), int(5 * sfreq))
        t = np.arange(max_idx) / sfreq
        fig = go.Figure()
        if raw_sig is not None:
            # Normalize raw for comparison if needed, or just plot
            fig.add_trace(go.Scatter(x=t, y=raw_sig[:max_idx], name="Raw", line=dict(color="rgba(255,255,255,0.3)", width=1)))
        fig.add_trace(go.Scatter(x=t, y=filt_sig[:max_idx], name="Filtered", line=dict(color=COLORS["primary"])))
        set_layout(fig, "ECG Signal (Raw vs Filtered)")
        try: charts["ecg_raw_filt"] = fig.to_image(format="png", width=800, height=350, engine="kaleido")
        except: pass
        
    # 2. R-Peak Detection Overlay
    rpeaks = st.session_state.get("rpeaks", {}).get(filename)
    if filt_sig is not None and rpeaks is not None:
        max_idx = min(len(filt_sig), int(10 * sfreq))
        t = np.arange(max_idx) / sfreq
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=t, y=filt_sig[:max_idx], name="ECG", line=dict(color=COLORS["primary"], width=1)))
        rp_in = rpeaks[rpeaks < max_idx]
        fig.add_trace(go.Scatter(x=rp_in / sfreq, y=filt_sig[rp_in], mode="markers", 
                                 name="R-Peaks", marker=dict(color=COLORS["error"], size=10, symbol="triangle-up")))
        set_layout(fig, "R-Peak Detection Overlay")
        try: charts["rpeaks"] = fig.to_image(format="png", width=800, height=350, engine="kaleido")
        except: pass

    # 3. RR Tachogram
    clean_rr = st.session_state.get("clean_rr_intervals", {}).get(filename)
    if clean_rr is not None:
        fig = go.Figure()
        fig.add_trace(go.Scatter(y=clean_rr, mode='lines+markers', line=dict(color=COLORS["primary_dim"]), name="RR"))
        set_layout(fig, "RR Tachogram", xaxis_title="Beat Index", yaxis_title="RR Interval (ms)")
        try: charts["rr_tachogram"] = fig.to_image(format="png", width=800, height=350, engine="kaleido")
        except: pass

    # 4. Ectopic Correction (Raw vs Clean RR)
    raw_rr = st.session_state.get("raw_rr_intervals", {}).get(filename)
    if raw_rr is not None and clean_rr is not None:
        fig = go.Figure()
        fig.add_trace(go.Scatter(y=raw_rr, name="Raw RR", line=dict(color="rgba(255,180,171,0.4)", width=1)))
        fig.add_trace(go.Scatter(y=clean_rr, name="Clean RR", line=dict(color=COLORS["secondary_fixed"])))
        set_layout(fig, "Ectopic Correction (Raw vs Clean RR)", xaxis_title="Beat Index", yaxis_title="RR (ms)")
        try: charts["ectopic_corr"] = fig.to_image(format="png", width=800, height=350, engine="kaleido")
        except: pass

    # 5. PSD (Frequency Domain)
    psd_raw = st.session_state.get("psd_data", {}).get(filename)
    if psd_raw is not None:
        freqs_p, psd_p = psd_raw
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=freqs_p, y=psd_p, fill="tozeroy", line=dict(color=COLORS["secondary_fixed"])))
        set_layout(fig, "Power Spectral Density (LF/HF)", xaxis_title="Frequency (Hz)", yaxis_title="Power (ms²/Hz)")
        try: charts["psd"] = fig.to_image(format="png", width=800, height=350, engine="kaleido")
        except: pass

    # 6. Poincare Plot
    if clean_rr is not None and len(clean_rr) > 2:
        rn, rn1 = clean_rr[:-1], clean_rr[1:]
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=rn, y=rn1, mode="markers", marker=dict(color=COLORS["primary_dim"], size=4, opacity=0.5)))
        set_layout(fig, "Poincaré Plot (Non-linear)", xaxis_title="RR(n) ms", yaxis_title="RR(n+1) ms")
        fig.update_layout(width=500, height=500)
        try: charts["poincare"] = fig.to_image(format="png", width=500, height=500, engine="kaleido")
        except: pass

    # 7. DFA Plot
    if clean_rr is not None and len(clean_rr) > 32:
        dfa_res = detrended_fluctuation_analysis(clean_rr)
        scales, fluct = dfa_res.get("scales", []), dfa_res.get("fluct", [])
        if len(scales) > 3:
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=np.log10(scales), y=np.log10(fluct), mode='markers+lines', marker=dict(color=COLORS["primary_dim"])))
            
            # Add short-term alpha1 line
            a1 = dfa_res.get("alpha1")
            if a1 and np.isfinite(a1):
                mask = (scales >= 4) & (scales <= 16)
                if np.sum(mask) >= 2:
                    lx = np.log10(scales[mask])
                    ly = np.log10(fluct[mask])
                    c = np.polyfit(lx, ly, 1)
                    x_line = np.array([lx.min(), lx.max()])
                    fig.add_trace(go.Scatter(x=x_line, y=np.polyval(c, x_line), mode='lines', name=f"α1={a1:.2f}", line=dict(color=COLORS["secondary_fixed"], dash='dash')))
            
            set_layout(fig, "Detrended Fluctuation Analysis (DFA)", xaxis_title="log10(Scale n)", yaxis_title="log10(F(n))")
            try: charts["dfa"] = fig.to_image(format="png", width=800, height=350, engine="kaleido")
            except: pass

    return charts

def _safe(v):
    if isinstance(v, (float, np.float64, np.float32)): return f"{v:.3f}"
    return "N/A" if v is None else str(v)


def build_pdf_report(metrics_dict: dict, settings: dict, sqi_cache: dict) -> bytes:
    import io as _io
    import tempfile, os as _os
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors as rl_colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                     Table, TableStyle, Image as RLImage, PageBreak)
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    # Register Unicode font
    import pathlib as _pl
    FONT_NAME = "DejaVu"
    try:
        import matplotlib
        fpath = _pl.Path(matplotlib.get_data_path()) / "fonts" / "ttf" / "DejaVuSans.ttf"
        if fpath.exists():
            pdfmetrics.registerFont(TTFont(FONT_NAME, str(fpath)))
        else:
            FONT_NAME = "Helvetica" # Fallback
    except: FONT_NAME = "Helvetica"

    buf = _io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, margin=1.5*cm)
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", fontName=FONT_NAME, fontSize=22, spaceAfter=14, textColor=rl_colors.HexColor("#003366"), alignment=1)
    h2 = ParagraphStyle("h2", fontName=FONT_NAME, fontSize=16, spaceAfter=10, textColor=rl_colors.HexColor("#1a5276"), spaceBefore=12)
    body = ParagraphStyle("body", fontName=FONT_NAME, fontSize=10, leading=12)

    story = [Paragraph("ECG & HRV Analysis Report", h1), Spacer(1, 1*cm)]
    
    for fname, m in metrics_dict.items():
        sqi = sqi_cache.get(fname, {})
        story.append(Paragraph(f"Analysis for File: {fname}", h2))
        
        # Section: Global Summary
        story.append(Paragraph("<b>Global Analysis Summary</b>", body))
        summary_data = [
            ["Metric", "Value", "Clinical Significance"],
            ["Mean HR", f"{m.get('Mean HR (bpm)', 'N/A')}", "Average Heart Rate"],
            ["SDNN", _safe(m.get('SDNN (ms)')), "Overall Autonomic Regulation"],
            ["RMSSD", _safe(m.get('RMSSD (ms)')), "Parasympathetic Activity (Vagal Tone)"],
            ["LF/HF Ratio", _safe(m.get('LF/HF Ratio')), "Sympathovagal Balance"],
            ["Signal Quality", sqi.get('quality_label', 'N/A'), f"SQI: {sqi.get('overall_sqi','N/A')}"]
        ]
        t_sum = Table(summary_data, colWidths=[4*cm, 4*cm, 8*cm])
        t_sum.setStyle(TableStyle([
            ('GRID', (0,0), (-1,-1), 0.5, rl_colors.grey),
            ('BACKGROUND', (0,0), (-1,0), rl_colors.HexColor("#d5e8f7")),
            ('FONTNAME', (0,0), (-1,0), FONT_NAME + "-Bold" if FONT_NAME != "Helvetica" else "Helvetica-Bold"),
        ]))
        story.append(t_sum)
        story.append(Spacer(1, 0.6*cm))

        # Section: Time-Domain
        story.append(Paragraph("Time-Domain Metrics", body))
        data = [["Metric", "Value", "Unit"]]
        for k, unit in [("Mean RR", "ms"), ("SDNN", "ms"), ("RMSSD", "ms"), ("NN50", "beats"), ("pNN50", "%")]:
            val = m.get(k) or m.get(k+" (ms)") or m.get(k+" (%)") or m.get(k+" (beats)")
            data.append([k, _safe(val), unit])
        t = Table(data, colWidths=[6*cm, 5*cm, 5*cm])
        t.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, rl_colors.grey), ('BACKGROUND', (0,0), (-1,0), rl_colors.lightgrey)]))
        story.append(t)
        story.append(Spacer(1, 0.5*cm))

        # Section: Frequency-Domain
        story.append(Paragraph("Frequency-Domain Metrics (PSD)", body))
        data_f = [["Metric", "Value", "Unit"]]
        for k, unit in [("VLF Power", "ms²"), ("LF Power", "ms²"), ("HF Power", "ms²"), ("LF/HF Ratio", "ratio"), ("Total Power", "ms²")]:
            val = m.get(k) or m.get(k+" (ms2)") or m.get(k+" (ms²)")
            data_f.append([k, _safe(val), unit])
        t_f = Table(data_f, colWidths=[6*cm, 5*cm, 5*cm])
        t_f.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, rl_colors.grey), ('BACKGROUND', (0,0), (-1,0), rl_colors.lightgrey)]))
        story.append(t_f)
        story.append(Spacer(1, 0.5*cm))

        # Section: Non-Linear
        story.append(Paragraph("Non-Linear HRV Metrics", body))
        data_nl = [["Metric", "Value", "Description"]]
        for k, desc in [("SD1", "Short-term variability"), ("SD2", "Long-term variability"), 
                        ("SD1/SD2", "Short/Long term ratio"), ("DFA α1", "Short-term fractal exponent"),
                        ("Sample Entropy", "Signal complexity")]:
            val = m.get(k) or m.get(k+" (ms)") or m.get(k+" (ms2)")
            data_nl.append([k, _safe(val), desc])
        t_nl = Table(data_nl, colWidths=[4*cm, 4*cm, 8*cm])
        t_nl.setStyle(TableStyle([('GRID', (0,0), (-1,-1), 0.5, rl_colors.grey), ('BACKGROUND', (0,0), (-1,0), rl_colors.lightgrey)]))
        story.append(t_nl)
        story.append(Spacer(1, 0.5*cm))

        # Interpretation
        story.append(Paragraph("<b>Detailed Clinical Assessment</b>", body))
        interp = interpret_hrv(m, m)
        assess_text = (
            f"The analyzed signal for <b>{fname}</b> shows an {interp.get('sdnn_class','—')}. "
            f"Regarding vagal regulation, the findings indicate a {interp.get('autonomic','—').lower()}. "
            f"The sympathovagal balance, as measured by the LF/HF ratio, suggests {interp.get('lf_hf_class','—').lower()}."
        )
        story.append(Paragraph(assess_text, body))
        story.append(Spacer(1, 0.5*cm))

        # Physiology Reference Table
        story.append(Paragraph("<b>Physiology Reference Guide (Normal Resting Ranges)</b>", body))
        ref_data = [
            ["Metric", "Normal Range", "Clinical Relevance"],
            ["HR (Mean)", "60 - 100 bpm", "Resting heart rate"],
            ["SDNN", "50 - 100 ms", "Overall autonomic health"],
            ["RMSSD", "20 - 50 ms", "Vagal tone / recovery"],
            ["LF/HF Ratio", "1.0 - 2.0", "Sympathovagal balance"],
            ["DFA α1", "0.9 - 1.2", "Healthy fractal scaling"]
        ]
        t_ref = Table(ref_data, colWidths=[4*cm, 4*cm, 8*cm])
        t_ref.setStyle(TableStyle([
            ('GRID', (0,0), (-1,-1), 0.5, rl_colors.grey),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('BACKGROUND', (0,0), (-1,0), rl_colors.whitesmoke)
        ]))
        story.append(t_ref)
        story.append(Spacer(1, 1*cm))

        # MANDATORY GRAPHS
        charts = _generate_report_charts(fname)
        chart_order = [
            ("ecg_raw_filt", "Figure 1: ECG Signal (Raw vs Filtered)"),
            ("rpeaks", "Figure 2: R-Peak Detection Overlay"),
            ("rr_tachogram", "Figure 3: RR Tachogram (Interval Variation)"),
            ("ectopic_corr", "Figure 4: Ectopic Beat Correction"),
            ("psd", "Figure 5: Power Spectral Density (LF/HF Bands)"),
            ("poincare", "Figure 6: Poincaré Plot (Non-linear Scatter)"),
            ("dfa", "Figure 7: Detrended Fluctuation Analysis (DFA)")
        ]
        
        for ckey, clabel in chart_order:
            if ckey in charts:
                story.append(Paragraph(clabel, body))
                with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                    tmp.write(charts[ckey])
                    tpath = tmp.name
                # Adjust size for poincare and dfa to fit well
                c_height = 6*cm
                if ckey == "poincare": c_height = 10*cm
                story.append(RLImage(tpath, width=16*cm, height=c_height))
                _os.remove(tpath)
                story.append(Spacer(1, 0.4*cm))
        
        story.append(PageBreak())

    doc.build(story)
    return buf.getvalue()


def build_docx_report(metrics_dict: dict, settings: dict, sqi_cache: dict) -> bytes:
    import docx
    from docx.shared import Inches, Pt
    import io
    doc = docx.Document()
    doc.add_heading("ECG & HRV Analysis Report", 0)
    
    for fname, m in metrics_dict.items():
        doc.add_heading(f"Analysis: {fname}", level=1)
        
        # Global Summary
        doc.add_heading("Global ECG Summary", level=2)
        doc.add_paragraph(f"Mean Heart Rate: {m.get('Mean HR (bpm)', 'N/A')} bpm")
        doc.add_paragraph(f"SDNN (Overall HRV): {_safe(m.get('SDNN (ms)'))} ms")
        doc.add_paragraph(f"RMSSD (Vagal Tone): {_safe(m.get('RMSSD (ms)'))} ms")
        
        charts = _generate_report_charts(fname)
        
        # 1. ECG Signal Section
        doc.add_heading("1. ECG Signal (Raw vs Filtered)", level=2)
        if "ecg_raw_filt" in charts:
            doc.add_picture(io.BytesIO(charts["ecg_raw_filt"]), width=Inches(6))

        # 2. R-Peak Detection
        doc.add_heading("2. R-Peak Detection Overlay", level=2)
        if "rpeaks" in charts:
            doc.add_picture(io.BytesIO(charts["rpeaks"]), width=Inches(6))

        # 3. RR Interval Analysis
        doc.add_heading("3. RR Interval Analysis & Tachogram", level=2)
        if "rr_tachogram" in charts:
            doc.add_picture(io.BytesIO(charts["rr_tachogram"]), width=Inches(6))

        # 4. Ectopic Correction
        doc.add_heading("4. Ectopic Beat Correction", level=2)
        if "ectopic_corr" in charts:
            doc.add_picture(io.BytesIO(charts["ectopic_corr"]), width=Inches(6))

        # 5. Frequency Domain
        doc.add_heading("5. Frequency Domain (PSD)", level=2)
        if "psd" in charts:
            doc.add_picture(io.BytesIO(charts["psd"]), width=Inches(6))

        # 6. Non-linear HRV
        doc.add_heading("6. Non-linear HRV (Poincaré & DFA)", level=2)
        if "poincare" in charts:
            doc.add_picture(io.BytesIO(charts["poincare"]), width=Inches(4))
        if "dfa" in charts:
            doc.add_picture(io.BytesIO(charts["dfa"]), width=Inches(6))

        # Tables
        doc.add_heading("Full Metrics Summary", level=2)
        table = doc.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Metric'
        hdr_cells[1].text = 'Value'
        
        metrics_to_list = [
            "Mean RR", "SDNN", "RMSSD", "NN50", "pNN50", 
            "LF Power", "HF Power", "LF/HF Ratio",
            "SD1", "SD2", "DFA α1", "Sample Entropy"
        ]
        for k in metrics_to_list:
            val = m.get(k) or m.get(k+" (ms)") or m.get(k+" (%)") or m.get(k+" (ms2)") or m.get(k+" (ms²)")
            row_cells = table.add_row().cells
            row_cells[0].text = k
            row_cells[1].text = _safe(val)

        # Interpretation
        doc.add_heading("Clinical Interpretation", level=2)
        interp = interpret_hrv(m, m)
        doc.add_paragraph(f"Analysis Status: {interp.get('sdnn_class','—')}")
        doc.add_paragraph(f"Vagal Activity: {interp.get('autonomic','—')}")
        doc.add_paragraph(f"Sympathovagal Balance: {interp.get('lf_hf_class','—')}")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    inject_stitch_theme()
    render_sidebar_settings()
    sentinel_header("Report Generation", badge="Export")
    pipeline_status_bar("HRV")

    metrics_dict = st.session_state.get("metrics",   {})
    sqi_cache    = st.session_state.get("sqi_cache", {})
    settings     = {k: st.session_state.get(k) for k in [
        "sfreq", "lowcut", "highcut", "filter_order", "rpeak_method", "remove_ectopic", "ectopic_method",
        "lf_min", "lf_max", "hf_min", "hf_max",
    ]}

    if not metrics_dict:
        st.warning("No analysis results found. Complete the pipeline first.")
        return

    section_header("Export Options")
    
    col_pdf, col_docx, _ = st.columns([1, 1, 2])
    
    with col_pdf:
        if st.button("Generate PDF Report", use_container_width=True):
            with st.spinner("Building PDF..."):
                st.session_state["pdf_bytes"] = build_pdf_report(metrics_dict, settings, sqi_cache)
                
        if "pdf_bytes" in st.session_state:
            st.download_button("Download PDF", data=st.session_state["pdf_bytes"], file_name="HRV_Report.pdf", mime="application/pdf", use_container_width=True)

    with col_docx:
        if st.button("Generate DOCX Report", use_container_width=True):
            with st.spinner("Building Word Doc..."):
                st.session_state["docx_bytes"] = build_docx_report(metrics_dict, settings, sqi_cache)
                
        if "docx_bytes" in st.session_state:
            st.download_button("Download DOCX", data=st.session_state["docx_bytes"], file_name="HRV_Report.docx", use_container_width=True)

    st.markdown("---")
    section_header("Clinical Interpretation Summary")
    for fname, m in metrics_dict.items():
        interp  = interpret_hrv(m, m)
        sqi     = sqi_cache.get(fname, {})
        lf_hf   = m.get("LF/HF Ratio", float('nan'))
        sqi_lbl = sqi.get("quality_label", "—") if sqi else "—"
        st.markdown(f"""
        <div style="background:#1a1c1f;border:1px solid #1e2023;border-left:4px solid #c3f400;border-radius:0.375rem;padding:1rem;margin-bottom:0.75rem;">
          <div style="display:flex;justify-content:space-between;margin-bottom:0.4rem;">
            <span style="font-weight:800;color:#849396;">{fname}</span>
            <span style="background:#c3f400;color:#000;font-size:0.6rem;padding:0.15rem 0.5rem;border-radius:0.2rem;">SQI: {sqi_lbl}</span>
          </div>
          <div style="font-size:0.8rem;color:#bac9cc;">
            <strong>HRV Status:</strong> {interp.get('sdnn_class','—')}<br>
            <strong>Vagal Tone:</strong> {interp.get('autonomic','—')}<br>
            <strong>Sympathovagal (LF/HF={lf_hf:.2f}):</strong> {interp.get('lf_hf_class','—')}
          </div>
        </div>""", unsafe_allow_html=True)


if __name__ == "__main__":
    main()
